"use client";
import { useRef, useState } from "react";
import emailjs from "@emailjs/browser";
import { Copy, ArrowUpRight } from "lucide-react";
import { profile } from "@/constants/profile";
export default function Contacts(){const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");const [copied,setCopied]=useState("");const lock=useRef(false);const lastSent=useRef(0);
const service=process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID;const template=process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID;const key=process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY;const configured=Boolean(service&&template&&key);
async function copy(){try{await navigator.clipboard.writeText(profile.email);setCopied("Email copied")}catch{setCopied("Please select and copy the email address above.")}}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;const form=e.currentTarget;const data=new FormData(form);if(data.get("website"))return;if(Date.now()-lastSent.current<60000){setStatus("Please wait a minute before sending another message.");return}const name=String(data.get("name")||"").trim();const email=String(data.get("email")||"").trim();const message=String(data.get("message")||"").trim();if(!name||!email||!message){setStatus("Please fill in every field.");return}lock.current=true;setBusy(true);setStatus("");try{await emailjs.send(service!,template!,{from_name:name,from_email:email,reply_to:email,message},key!);lastSent.current=Date.now();form.reset();setStatus("Thanks! Your message has been sent.")}catch{setStatus("Your message could not be sent. Please use the email link instead.")}finally{lock.current=false;setBusy(false)}}
return <section id="contact" className="section shell contact-grid"><div><p className="eyebrow">04 / LET’S CONNECT</p><h2>Have something<br/><span>in mind?</span></h2><p className="contact-intro">I’m open to backend engineering and AI application opportunities. Let’s talk about what you’re building.</p><a className="email-link" href={`mailto:${profile.email}`}>{profile.email} <ArrowUpRight size={18}/></a><button className="copy-button" onClick={copy}><Copy size={15}/> Copy email</button><p className="feedback" role="status">{copied}</p><div className="socials"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href={profile.github} target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></div><div className="contact-panel"><h3>Start a conversation</h3>{configured?<form onSubmit={submit}><div className="form-row"><label htmlFor="name">Your name<input id="name" name="name" autoComplete="name" required maxLength={100}/></label><label htmlFor="email">Email address<input id="email" name="email" type="email" autoComplete="email" required maxLength={254}/></label></div><label htmlFor="message">What would you like to discuss?<textarea id="message" name="message" rows={5} required maxLength={4000}/></label><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><button className="btn primary" disabled={busy} type="submit">{busy?"Sending…":"Send message ↗"}</button><p role="status" className="feedback">{status}</p></form>:<div className="email-fallback"><p>The best way to reach me is by email. Include the role or project you have in mind, and a little about your team.</p><a className="btn primary" href={`mailto:${profile.email}?subject=Portfolio%20enquiry`}>Write an email <ArrowUpRight size={17}/></a></div>}</div></section>}
